version: 2
updates:
  - package-ecosystem: cargo
    directory: /zeus
    schedule:
      interval: weekly
      day: monday
      time: "00:00"
      timezone: Etc/UTC
    groups:
      rust-dependencies:
        patterns: ["*"]
    open-pull-requests-limit: 5

  - package-ecosystem: npm
    directory: /sidecar
    schedule:
      interval: weekly
      day: monday
      time: "00:00"
      timezone: Etc/UTC
    groups:
      sidecar-dependencies:
        patterns: ["*"]
    open-pull-requests-limit: 5

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "00:00"
      timezone: Etc/UTC
    groups:
      actions:
        patterns: ["*"]
    open-pull-requests-limit: 5

  - package-ecosystem: rust-toolchain
    directory: /zeus
    schedule:
      interval: weekly
      day: monday
      time: "00:00"
      timezone: Etc/UTC
    open-pull-requests-limit: 2
