[package]
name = "zeus-node"
version = "0.0.1"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[[bin]]
name = "zeus-node"
path = "src/main.rs"

[dependencies]
zeus-client.workspace = true
zeus-proto.workspace = true
zeus-usage.workspace = true
getrandom.workspace = true
rusqlite.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
tokio.workspace = true

[dev-dependencies]
tempfile.workspace = true
