[package]
name = "diri-engine"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
alacritty_terminal.workspace = true
diri-proto.workspace = true
regex.workspace = true
serde.workspace = true
serde_json.workspace = true

[target.'cfg(unix)'.dependencies]
libc = "0.2"

[dev-dependencies]
tempfile.workspace = true

[target.'cfg(unix)'.dev-dependencies]
libc = "0.2"
